USE EMPLEADOS;
/*PRACTICA 7.1 - GROUP BY - HAVING*/
1. HALLAR PARA CADA DEPART EL SALARIO MEDIO
SELECT NUMDE, AVG(SALAR)
FROM TEMPLE
GROUP BY NUMDE
ORDER BY NUMDE;

2.- ¿CUÁNTOS EMPLEADOS HAY EN LOS DEPARTAMENTOS 100 Y 110?
SELECT NUMDE AS "NUMDERO DEL DEP", COUNT(*) AS "SALARIO PROMEDIO DE CADA DEP"
FROM TEMPLE
GROUP BY NUMDE
HAVING NUMDE=100 OR NUMDE=110;

3.- PARA CADA DEPART CALCULAR SALARIO MIN, MAX Y PROMEDIO
SELECT NUMDE, MIN(SALAR), MAX(SALAR), AVG(SALAR)
FROM TEMPLE
GROUP BY NUMDE;

4.- AGRUPANDO POR DEP Y POR NUMHI, CALCULAR CUANTOS EMP HAY 
PARA LOS DEP 100 Y 110

SELECT NUMDE, NUMHI, COUNT(*)
FROM TEMPLE
GROUP BY NUMDE, NUMHI
HAVING NUMDE=100 OR NUMDE=110
ORDER BY NUMDE;

5.- 
SELECT NUMDE, MIN(SALAR), MAX(SALAR), AVG(SALAR)
FROM TEMPLE
GROUP BY NUMDE
HAVING NUMDE=100;

5.- 
SELECT NUMDE, MIN(SALAR), MAX(SALAR), AVG(SALAR)
FROM TEMPLE
GROUP BY NUMDE
HAVING NUMDE=100;